@extends('admin.layouts.app')
@section('title', 'ইমেইল হিস্ট্রি')
@section('header', '🕘 ইমেইল হিস্ট্রি')
@section('content')
<div class="space-y-5">
 <div class="flex flex-wrap items-center justify-between gap-3"><form method="GET" class="flex gap-2"><input name="q" value="{{ request('q') }}" placeholder="ইমেইল/সাবজেক্ট" class="rounded-xl border border-charcoal/15 bg-white px-4 py-2 text-sm"><select name="status" class="rounded-xl border border-charcoal/15 bg-white px-4 py-2 text-sm"><option value="">সব</option><option value="sent" @selected(request('status')==='sent')>Sent</option><option value="failed" @selected(request('status')==='failed')>Failed</option><option value="pending" @selected(request('status')==='pending')>Pending</option></select><button class="rounded-xl bg-charcoal px-4 py-2 text-sm font-bold text-white">ফিল্টার</button></form><a href="{{ route('admin.emails.send') }}" class="rounded-full bg-gradient-warm px-5 py-2 text-sm font-bold text-white shadow-warm">✉️ নতুন ইমেইল</a></div>
 <div class="overflow-hidden rounded-2xl border border-charcoal/10 bg-white shadow-soft"><table class="w-full text-sm"><thead class="bg-cream text-left"><tr><th class="p-3">সময়</th><th class="p-3">প্রাপক</th><th class="p-3">টেমপ্লেট</th><th class="p-3">সাবজেক্ট</th><th class="p-3">স্ট্যাটাস</th><th class="p-3">এরর</th></tr></thead><tbody class="divide-y divide-charcoal/8">@forelse($logs as $log)<tr><td class="p-3 text-xs text-charcoal/50">{{ optional($log->sent_at ?? $log->created_at)->format('d M Y h:i A') }}</td><td class="p-3"><b>{{ $log->recipient_name }}</b><br><span class="text-xs text-charcoal/50">{{ $log->recipient_email }}</span></td><td class="p-3">{{ $log->template->name ?? '—' }}</td><td class="p-3">{{ $log->subject }}</td><td class="p-3"><span class="rounded-full px-2 py-1 text-xs font-bold {{ $log->status==='sent' ? 'bg-green-100 text-green-700' : ($log->status==='failed' ? 'bg-red-100 text-red-700' : 'bg-yellow-100 text-yellow-700') }}">{{ $log->status }}</span></td><td class="p-3 text-xs text-red-600">{{ Str::limit($log->error_message, 80) }}</td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-charcoal/40">কোনো হিস্ট্রি নেই</td></tr>@endforelse</tbody></table><div class="p-4">{{ $logs->links() }}</div></div>
</div>
@endsection
